version: '3.9'
 services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: aspnet_api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000

frontend:
 build:
 context: ./frontend
 dockerfile: Dockerfile
 container_name: angular_frontend
 ports:
  - "4200:80"
 nginx:
  image: nginx:latest
  container_name: nginx_reverse
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "80:80"
    - "443:443"
  depends_on:
    - api
    - frontend